accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings  
from django.conf.urls.static import static
from accounts import views as mainview
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',mainview.login),
    path('posts/',include('posts.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('<username>/',views.index,name='index'),
    path('<username>/create/',views.create,name='create')

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
# Create your models here.

def user_profile_path(instance,filename):
    return 'profile/{0}/{1}'.format(instance.username,filename)


class User(AbstractUser):
    nickname = models.CharField(max_length=10,verbose_name='닉네임')
    profile = models.ImageField(upload_to=user_profile_path,default='default/default_img.jpg',verbose_name='프로필 이미지')
    intro = models.TextField(verbose_name='한줄 소개',blank=True)
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='followings')
    profile_thumbnail = ImageSpecField(source='profile',
                          processors=[Thumbnail(300, 300)],
                          format='JPEG',
                          options={'quality': 60})

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
# Create your models here.

class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='post')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='like_posts')


class PostComment(models.Model):
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='postcomment')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='like_comments')


def post_image_path(instance,filename):
    return 'profile/{0}/posts/{1}'.format(instance.post.user.username,filename)

class PostImage(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='postimage')
    image = models.ImageField(upload_to=post_image_path,verbose_name='포스트이미지')
    thumbnail = ImageSpecField(source='image',
                        processors=[Thumbnail(300, 300)],
                        format='JPEG',
                        options={'quality': 60})


class Tag(models.Model):
    name = models.CharField(max_length=50)
    posts = models.ManyToManyField(Post,related_name='tags')

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username','nickname']

posts/forms.py
from .models import Post,PostImage
from django import forms

class PostForm(forms.ModelForm):
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    class Meta:
        model = Post
        fields = ('content','images')

class PostImageForm(forms.ModelForm):
    class Meta:
        model = PostImage
        fields = ('image',)

accounts/views.py
from django.shortcuts import render,redirect
from .forms import UserCustomCreationForm

from django.contrib.auth.forms import AuthenticationForm

from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# Create your views here.
def index(request):
    return render(request,'accounts/index.html')


def signup(request):
    if request.method == 'POST':
        form = UserCustomCreationForm(request.POST)
        print(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('posts:index',request.user.username)
    else:
        form = UserCustomCreationForm()
    context = {
        'form': form,
    }
    return render(request,'accounts/signup.html',context)

def login(request):

    if request.method =='POST':
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            auth_login(request,form.get_user())

            return redirect('posts:index',request.user.username)

    else:
        form = AuthenticationForm()
    context={
        'form':form
    }
    return render(request,'accounts/login.html',context)


def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

posts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import get_user_model
from django.forms import modelformset_factory
from .forms import PostForm,PostImageForm
from .models import PostImage
# Create your views here.
User = get_user_model()
def index(request,username):
    main_user = User.objects.get(username=username)
    posts = main_user.post.all()

    context = {
        'main_user' : main_user,
        'posts' : posts
    }
    return render(request,'posts/index.html',context)

def create(request,username):
    if request.user.username == username:
        if request.method == 'POST':
            form = PostForm(request.POST,request.FILES or None)
            if form.is_valid():
                post = form.save(commit=False)
                post.user = request.user
                post.save()
                if request.FILES:
                    for img in request.FILES.getlist('images'):
                        postimg = PostImage(post=post,image=img)
                        postimg.save()
                
                return redirect('posts:index',username)
        else:
            form = PostForm()

        context = {
            'form' : form,
        }
        return render(request,'posts/create.html',context)
    else:
        return redirect('posts:index',username)

accounts/templates/accounts/index.html
{% extends 'base_home.html' %}


{% block content %}
  <p>이름 : {{request.user.username}}</p>
  <p></p>
  <img src="{{request.user.profile.url}}" alt="" width="200px">

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base_home.html'%}

{% block content %}

  <div id="loginpage">
    <div class="col-12 border mt-5" style="height: 380px;">
      <div class="my-5">
        <h1 class="login_h1">Instagram</h1>
      </div>
      <form action="" method="POST" class="d-flex flex-column" >
        {% csrf_token %}
        <div class=" my-1">
            {{form.username}}
        </div>
        <div class="my-1">
          {{form.password}}
        </div>
        <button id="loginbtn" class="btn btn-primary w-75 mx-auto my-1" disabled=true>로그인</button>
      </form>
    </div>
    <hr>
    <div class="w-100 border py-5 my-1" >
      <p>계정이 없으신가요?<a href="{% url 'accounts:signup' %}">가입하기</a></p>
    </div>
  </div>
{% endblock %}

{% block script %}
<script>
  const inputId = document.querySelector('#id_username')
  const inputPassword = document.querySelector('#id_password')
  const submitBtn = document.querySelector('#loginbtn')

  inputId.classList.add('w-75')
  inputId.classList.add('py-1')
  inputId.placeholder = '아이디를 입력해주세요'
  inputPassword.classList.add('w-75')
  inputPassword.classList.add('py-1')
  inputPassword.placeholder = '비밀번호를 입력해주세요'
  inputId.addEventListener('input',checkinput)
  inputPassword.addEventListener('input',checkinput)
  function checkinput(){
    var inputIdValue = inputId.value
    var inputPasswordValue = inputPassword.value
    if (inputIdValue === '' || inputPasswordValue === ''){
      console.log('비활성화')
      submitBtn.disabled = true

    } else {
      console.log('활성화')
      submitBtn.disabled = false
    }

  }
</script>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_home.html'%}

{% block content %}

  <div id="loginpage">
    <div class="col-12 border" >
      <div class="my-5">
        <h1 class="login_h1">Instagram</h1>
      </div>
      <p style="font-size: 17px;">친구들의 사진과 동영상을 보려면 가입하세요</p>
      <form action="" method="POST" class="d-flex flex-column" >
        {% csrf_token %}
        <div class=" my-1">
            {{form.username}}
        </div>
        <div class=" my-1">
          {{form.nickname}}
        </div>
        <div class="my-1">
          {{form.password1}}
        </div>
        <div class="my-1">
          {{form.password2}}
        </div>
        <button id="signbtn" class="btn btn-primary w-75 mx-auto my-1" disabled=true>가입</button>
      </form>
      <div class="mt-3 py-1" style="font-size: 0.5rem;">
        가입하면 Instagram의 약관, 데이터정책 및 쿠키 정책에 동의하게 됩니다.
      </div>
    </div>
    <hr>
    <div class="w-100 border py-5 my-1" >
      <p>계정이 있으신가요?<a href="{% url 'accounts:login' %}">로그인</a></p>
    </div>
  </div>
{% endblock %}

{% block script %}
<script>
  const inputId = document.querySelector('#id_username')
  const inputNickname = document.querySelector('#id_nickname')
  const inputPassword = document.querySelector('#id_password1')
  const submitBtn = document.querySelector('#signbtn')
  const inputPassword2 = document.querySelector('#id_password2')

  inputId.classList.add('w-75')
  inputId.classList.add('py-1')
  inputId.placeholder = '아이디를 입력해주세요'
  inputId.addEventListener('input',checkinput)

  inputNickname.classList.add('w-75')
  inputNickname.classList.add('py-1')
  inputNickname.placeholder = '닉네임을 입력해주세요'
  inputNickname.addEventListener('input',checkinput)

  inputPassword.classList.add('w-75')
  inputPassword.classList.add('py-1')
  inputPassword.placeholder = '비밀번호를 입력해주세요'
  inputPassword.addEventListener('input',checkinput)

  inputPassword2.classList.add('w-75')
  inputPassword2.classList.add('py-1')
  inputPassword2.placeholder = '비밀번호를 다시 입력해주세요'
  inputPassword2.addEventListener('input',checkinput)

  function checkinput(){
    var inputIdValue = inputId.value
    var inputPasswordValue = inputPassword.value
    var inputPasswordValue2 = inputPassword2.value
    var inputNicknameValue = inputNickname.value
    if (inputIdValue === '' || inputPasswordValue === '' || inputPasswordValue2 === '' || inputNicknameValue === ''){
      console.log('비활성화')
      submitBtn.disabled = true

    } else {
      console.log('활성화')
      submitBtn.disabled = false
    }

  }
</script>
{% endblock %}

posts/templates/posts/create.html
{% extends 'base_main.html' %} 



{% block content %}
<form id="post_form" method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}
  {{form}}

  <input type="submit" name="submit" value="Submit" />

  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="width: 300px;">
    <div class="carousel-inner">
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

</form>


<script>
  const imgList = document.querySelector('#id_images')
  imgList.addEventListener('change',function(event){

    
    console.log(event.target.files)
    var cnt = 1
    for(var file of event.target.files){
      const maindiv = document.querySelector('.carousel-inner')
      if (cnt == 1){
        const innerDiv = document.createElement('div')
        innerDiv.classList.add('carousel-item','active')
        const innerImg = document.createElement('img')
        innerImg.width='300'
        console.log(innerImg)
        var reader = new FileReader()
        reader.onload = (function(aImg){
          return function(event){
            aImg.src = event.target.result
          }
        })(innerImg)
        reader.readAsDataURL(file)
        innerDiv.appendChild(innerImg)
        maindiv.appendChild(innerDiv)
      } else{
        const innerDiv = document.createElement('div')
        innerDiv.classList.add('carousel-item')
        const innerImg = document.createElement('img')
        innerImg.width='300'
        var reader = new FileReader()
        reader.onload = (function(aImg){
          return function(event){
            aImg.src = event.target.result
          }
        })(innerImg)
        reader.readAsDataURL(file)
        innerDiv.appendChild(innerImg)
        maindiv.appendChild(innerDiv)
      }
      cnt++
    }
  })
</script>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base_main.html' %}

{% block content %}
  <a href="{% url 'posts:create' main_user.username %}">새글 쓰기</a>
  <div class="container">
    <div class="row">
      <div class="col-12 mb-5" style="height: 40vh;">
        <div class="row">
          <div class="col-4">
            <div class="main_box mx-auto border">
              <img class="main_profile" src="{{main_user.profile.url}}" alt="">
            </div>
          </div>
          <div class="col-8">
            <h1>{{main_user.username}}
            {% if main_user == request.user %}
              <a href=""><button class="btn btn-default border font-weight-bold">프로필 편집</button></a>
            {% else %}
              <button class="btn btn-primary">팔로우</button>
            {% endif %}

            </h1>
            <hr>
            <div>
              {{main_user.intro}}
            </div>
          </div>
        </div>
      </div>

  {% for post in posts %}
    {{post.content}}
    {% if post.postimage %}
      {% for img in post.postimage.all %}
      <img src="{{img.image.url}}" width="400px" alt="">
      {% endfor %}
    {% endif %}
  {% endfor %}


    </div>
  </div>


  <script>
    const postArray = document.querySelectorAll('[data-type]')

    postArray.forEach((post)=>{
      post.addEventListener('click',(event)=>{
        history.pushState(null,'instagram',event.target.dataset.postid)
      })
    })
  </script>
{% endblock %}

templates/_base_main_navbar.html
{% load static %}
<div class="sticky-top bg-white">
  <div class="container ">
    <div class="row align-items-center"  style="height: 54px;">
      <div class="col-4 py-1">
        <img src="{% static 'img/instagram_banner.png' %}" alt="">
      </div>
      <div class="col-4">
        <input type="text" placeholder="검색">
      </div>
      <div id="navbar" class="col-4" style="height: 50%;">
        <ul class="nav">
          <a class="" href="{% url 'posts:index' request.user.username %}" >
            <li class="home-btn list-unstyled mt-1 nav-item ml-5">            
            </li>
          </a>
          <a class="" href="#" >
            <li class="like-btn list-unstyled mt-1 nav-item mx-4">            
            </li>
          </a>
          <a class="" href="#" >
            <li class="box list-unstyled nav-item mx-1">
              <img class="profile" src="{{ request.user.profile_thumbnail.url }}" alt="">
                 
            </li>
          </a>
        </ul>
      </div>
    </div>
  </div>
  <div class="border border-dark"></div>
</div>

templates/base_home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Instagram</title>
  <link rel="icon" href="{% static 'img/favicon.png' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/base_home.css' %}">
</head>
<body onload="checked()">

  <a href="{% url 'accounts:signup' %}">signup</a>
  <a href="{% url 'accounts:login' %}">login</a>
  <a href="{% url 'accounts:logout' %}">logout</a>
  <p>{{request.user}}</p>
  <div class="container">
    <div class="row main_body justify-content-center align-items-center">
      <div class="main_img">
        <div class="inner_img">
          <img class='img_car' width="240px" height="427px" src="{% static 'img/instagram_innerbackground1.jpg' %}" alt="">
          <img class='img_car' width="240px" height="427px" src="{% static 'img/instagram_innerbackground2.jpg' %}" alt="">
          <img class='img_car' width="240px" height="427px" src="{% static 'img/instagram_innerbackground3.jpg' %}" alt="">
          <img class='img_car' width="240px" height="427px" src="{% static 'img/instagram_innerbackground4.jpg' %}" alt="">
        </div>
      </div>
      {% block content %}
      {% endblock %}
    </div>
  </div>
  {% block script %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <script>
    var imagArray = document.querySelectorAll('.img_car')
    var cnt = 0
    function checked(){
      if (cnt == 4 ){
        cnt = 0
      }
      console.log(imagArray)
      temp = 0
      for (var tag of imagArray){

        if (temp === cnt){
          tag.classList.add('img_first')
          tag.classList.remove('img_last')

        } else if(temp === (cnt+1)%4){
          tag.classList.add('img_last')
          tag.classList.remove('img_first')
        }
          else{
          tag.classList.remove('img_last')
          tag.classList.remove('img_first')
        }
        temp++


      }
      // console.log(cnt)
      setTimeout(checked,5000)
      cnt++
    }

  </script>

</body>
</html>

templates/base_main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Instagram</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base_main.css' %}">
</head>
<body>
  {% include '_base_main_navbar.html' %}
  {% block content %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>